### ISSUE TITLE
psenum validatescript modification

### ISSUE THREAD

**Issue by davidhowell-tx** [mattifestation/PSReflect#3] opened 2016-01-07 15:24 UTC
I was having some issues with Get-ProcessStrings from PowerShell Arsenla with PSReflect.

The error I'm receiving is within the Get-SystemInfo function when it attempts to build a structure using the $ProcessorType variable. Stepping through the code I find that $ProcessorType variable is empty.  After a little testing I found that it's due to the output of New-InMemoryModule paired with psenum's ValidateScript on the $Module variable

From function psenum's $Module variable:
> [ValidateScript({($_ -is [Reflection.Emit.ModuleBuilder]) -or ($_ -is [Reflection.Assembly])})]

This needs to be:
> [ValidateScript({($_ -is [Reflection.Emit.ModuleBuilder]) -or ($_ -is [Reflection.Assembly]) -or ($_ -is [System.Reflection.RuntimeAssembly])})]

Object type returned from New-InMemoryModule:
> $Mod = New-InMemoryModule -ModuleName SysInfo
> $Mod.GetType()
> IsPublic IsSerial Name                                     BaseType
> -------- -------- ----                                     --------
> False    False    InternalAssemblyBuilder                  System.Reflection.RuntimeAssembly

Host Information:
I am running this on Windows 8.1 with PowerShell version 4

Thanks for all of your great work!

**Comment by mattifestation** [comment] 2016-01-13 19:01
Thanks for filing the issue. Unfortunately, I'm unable to reproduce the issue. I tested it on each version of PowerShell and Get-SystemInfo returns without error. An issue with testing `[System.Reflection.RuntimeAssembly]` is that RuntimeAssembly is not a publicly exposed type. To demonstrate that, try changing the ValidateScript block to the following:

```powershell
[ValidateScript({($_ -is [System.Reflection.RuntimeAssembly]) -or ($_ -is [Reflection.Emit.ModuleBuilder]) -or ($_ -is [Reflection.Assembly])})]
```

I have yet to see New-InMemoryModule return anything aside from an Assembly or ModuleBuilder. Hrm.

**Comment by mattifestation** [comment] 2016-06-04 19:12
Closing. Unable to reproduce. If you have any additional info on reproduction steps, let me know. Thanks. Also, note that a RuntimeAssembly will match when compared against a System.Reflection.Assembly type. `[Intptr].Assembly -is [System.Reflection.Assembly]`

**Closed by mattifestation** 2016-06-04 19:12 UTC
